FROM nginx:1.27-alpine

WORKDIR /usr/share/nginx/html
COPY index.html ./index.html
COPY styles.css ./styles.css
COPY app.js ./app.js
COPY js ./js
COPY data ./data

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
